### ISSUE TITLE
AES-SIV tag comparison should be constant time

### ISSUE THREAD

**Issue by twvd** [dorssel/dotnet-aes-extra#6]
Hi @dorssel,

That's a nice looking library! 

I believe the AES-SIV tag comparison:
https://github.com/dorssel/dotnet-aes-extra/blob/eb6da597c04fb41d6cf1d6bf34c2b1d198db4e1a/AesExtra/AesSiv.cs#L181
should be changed to a method that is guaranteed to be constant time.
Otherwise, an attacker may be able to easily forge a valid tag.

If this is difficult in .NET, it may be enough to simply do a second comparison to a tag calculated with a random (freshly generated every time) key.

Also, it appears there is a debug message left in, here: https://github.com/dorssel/dotnet-aes-extra/blob/eb6da597c04fb41d6cf1d6bf34c2b1d198db4e1a/AesExtra/AesSiv.cs#L129

**Comment by dorssel** [comment]
On the first part (timing attack), I disagree. By construct of the CMAC, any input change (ciphertext or associated data) will alter the corresponding CMAC indistinguishably from uniform random. This CMAC value is then used to again indistinguishably relate plaintext and ciphertext (AES-CTR is essentially a pseudorandom one-time-pad).

Formally: AES-CMAC is IND-CTXT secure, and AES-CTR is IND-CPA secure. Together they are IND-CCA secure. Indistinguishably here means: a partial match provides no information at all.

Forging either a plaintext to match the tag/IV, or forging the tag/IV to match a specific plaintext is therefore not "cumulative" (as would be the case of comparing two plaintexts).

For this reason, RFC 5297 has no further constant time restrictions; it is simply not required. (Of course the constant time restrictions for AES-CTR and AES-CMAC themselves still apply.)

Side note: if you know of a way such that partial matches of a hash/MAC would provide knowledge to make longer matches easier, I strongly suggest you start mining BitCoins...

**Comment by dorssel** [comment]
On part two: this was just to see if anyone would actually read the code. So ... you win a prize! 🍰 

(OK, I admit ... it is indeed a left-over debug message  ...)

**Comment by twvd** [comment]
Makes sense; neither T nor V is under direct control of an attacker. I did notice other implementations have constant time comparisons; e.g. OpenSSL:
https://github.com/openssl/openssl/blob/31b7f23d2f958491d46c8a8e61c2b77b1b546f3e/crypto/modes/siv128.c#L322

And pycryptodome:
https://github.com/Legrandin/pycryptodome/blob/99273ea596aa6fb4ae9f18f7efa17d6bb359f35b/lib/Crypto/Cipher/_mode_siv.py#L253

Which led me to raise the issue.

(happy I won myself some 🎂 at least!)

**Comment by dorssel** [comment]
Had another look at it.

And I stand corrected!

The proof for IND-CPA + IND-CTXT => IND-CCA is only valid if only one error return exists. See: Boldyreva et al., FSE 2013.

I'll fix it. Thanks for the report!
